version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: review-analysis-api
    environment:
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - review-analysis-network
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data
    command: python run.py

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: review-analysis-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - review-analysis-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

networks:
  review-analysis-network:
    driver: bridge

volumes:
  sqlite_data:
